# my config
version: 2.1
orbs:
  node: circleci/node@3.0.0
  docker: circleci/docker@1.4.0

jobs:
  testing:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: "Install npm dependencies"
          command: npm install --save
      - run:
          name: Run testing by jest for api
          command: npm run test
  build-and-push:
    environment:
      DOCKER_IMAGE: ngtrdai197/simple-api-circleci
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy:
    executor: docker/docker
    steps:
      - add_ssh_keys:
          fingerprints:
            - $SSH_KEY_FINGERPRINT
      - run: ssh -oStrictHostKeyChecking=no $DEPLOYED_USER@$DEPLOYED_SERVER './simple-api-circleci.sh'

workflows:
  my-pipeline:
    jobs:
      - testing
      - build-and-push:
          requires:
            - testing
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build-and-push
